version: 1
formatters:
  simple:
    format: "%(asctime)s.%(msecs)03d\t%(name)s\t%(levelname)s\t%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  notion_issues:
    level: INFO
    handlers: [console]
    propagate: no
  aio_api_sm:
    level: INFO
    handlers: [console]
    propagate: no
  github:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]
